name: C# CD

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: [self-hosted, Windows, X64]

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Application
        run: dotnet run